github: [hitechcloudvn, thanhan92-f1, Pho-Tue-SoftWare-Solutions-JSC]
patreon: Pho-Tue-SoftWare-Solutions-JSC
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:

