#!/usr/bin/env bash
# lib/setup-caddy.sh -- Optional Caddy reverse proxy setup for public domains.
set -euo pipefail

setup_caddy() {
    CADDY_ENABLED="false"
    export CADDY_ENABLED

    local primary_domain="${CADDY_DOMAIN:-}"
    local dashboard_domain="${CADDY_DASHBOARD_DOMAIN:-}"

    if [[ "${CLAWSPARK_DEFAULTS:-false}" != "true" ]] && [[ -z "${primary_domain}" && -z "${dashboard_domain}" ]]; then
        printf '\n'
        print_box \
            "${BOLD}Optional Caddy Reverse Proxy${RESET}" \
            "" \
            "Enter a public domain to install Caddy with automatic HTTPS." \
            "Leave the domain blank to skip Caddy setup." \
            "DNS for the domain must already point to this machine." \
            "Ports 80 and 443 must be reachable from the internet."
        primary_domain=$(prompt_input "Public domain for Chat UI and API (leave blank to skip)" "")
        dashboard_domain=$(prompt_input "Optional domain for ClawMetry dashboard" "")
    fi

    primary_domain=$(_trim_value "${primary_domain}")
    dashboard_domain=$(_trim_value "${dashboard_domain}")

    if [[ -n "${primary_domain}" ]] && ! _is_valid_domain "${primary_domain}"; then
        log_warn "Invalid Chat UI domain '${primary_domain}' -- skipping Caddy setup."
        return 0
    fi

    if [[ -n "${dashboard_domain}" ]] && ! _is_valid_domain "${dashboard_domain}"; then
        log_warn "Invalid dashboard domain '${dashboard_domain}' -- skipping dashboard proxy."
        dashboard_domain=""
    fi

    if [[ -z "${primary_domain}" && -z "${dashboard_domain}" ]]; then
        log_info "No public domain provided -- skipping Caddy setup."
        rm -f "${CLAWSPARK_DIR}/caddy-chat.url" "${CLAWSPARK_DIR}/caddy-dashboard.url" "${CLAWSPARK_DIR}/caddy.enabled"
        return 0
    fi

    if [[ -n "${primary_domain}" && "${primary_domain}" == "${dashboard_domain}" ]]; then
        log_info "Dashboard domain matches the main domain. Dashboard will be available at /metrics/ on ${primary_domain}."
        dashboard_domain=""
    fi

    if ! _install_caddy; then
        log_warn "Caddy installation failed -- skipping public domain setup."
        return 0
    fi

    if ! _write_caddy_config "${primary_domain}" "${dashboard_domain}"; then
        log_warn "Caddy configuration failed -- skipping public domain setup."
        return 0
    fi

    if ! _reload_caddy; then
        log_warn "Caddy could not be started or reloaded. Check logs for details."
        return 0
    fi

    CADDY_DOMAIN="${primary_domain}"
    CADDY_DASHBOARD_DOMAIN="${dashboard_domain}"
    CADDY_ENABLED="true"
    export CADDY_DOMAIN CADDY_DASHBOARD_DOMAIN CADDY_ENABLED

    _write_caddy_summary_files

    log_success "Caddy setup complete."
}

_install_caddy() {
    if check_command caddy; then
        log_success "Caddy is already installed."
        return 0
    fi

    if ! sudo -n true 2>/dev/null; then
        log_warn "sudo is required to install Caddy automatically."
        return 1
    fi

    log_info "Installing Caddy..."

    if check_command apt-get; then
        (
            sudo apt-get update && sudo apt-get install -y caddy
        ) >> "${CLAWSPARK_LOG}" 2>&1 &
        spinner $! "Installing Caddy via apt..."
    elif check_command dnf; then
        (sudo dnf install -y caddy) >> "${CLAWSPARK_LOG}" 2>&1 &
        spinner $! "Installing Caddy via dnf..."
    elif check_command yum; then
        (sudo yum install -y caddy) >> "${CLAWSPARK_LOG}" 2>&1 &
        spinner $! "Installing Caddy via yum..."
    elif check_command brew; then
        (brew install caddy) >> "${CLAWSPARK_LOG}" 2>&1 &
        spinner $! "Installing Caddy via Homebrew..."
    else
        log_warn "No supported package manager found for automatic Caddy installation."
        return 1
    fi

    if ! check_command caddy; then
        log_warn "Caddy binary was not found after installation."
        return 1
    fi

    log_success "Caddy installed."
    return 0
}

_write_caddy_config() {
    local primary_domain="$1"
    local dashboard_domain="$2"
    local caddyfile="/etc/caddy/Caddyfile"

    if [[ -z "${primary_domain}" && -z "${dashboard_domain}" ]]; then
        return 1
    fi

    if ! sudo mkdir -p /etc/caddy >> "${CLAWSPARK_LOG}" 2>&1; then
        log_warn "Could not create /etc/caddy directory."
        return 1
    fi

    local tmpfile
    tmpfile=$(mktemp)

    {
        echo "# Generated by clawspark installer"
        echo "{"
        echo "    auto_https on"
        echo "}"
        echo

        if [[ -n "${primary_domain}" ]]; then
            cat <<EOF
${primary_domain} {
    encode gzip zstd

    handle_path /metrics* {
        reverse_proxy 127.0.0.1:8900
    }

    reverse_proxy 127.0.0.1:18789
}
EOF
        fi

        if [[ -n "${dashboard_domain}" ]]; then
            cat <<EOF

${dashboard_domain} {
    encode gzip zstd
    reverse_proxy 127.0.0.1:8900
}
EOF
        fi
    } > "${tmpfile}"

    if ! sudo cp "${tmpfile}" "${caddyfile}" >> "${CLAWSPARK_LOG}" 2>&1; then
        rm -f "${tmpfile}"
        log_warn "Failed to write ${caddyfile}."
        return 1
    fi
    rm -f "${tmpfile}"

    if ! sudo caddy validate --config "${caddyfile}" >> "${CLAWSPARK_LOG}" 2>&1; then
        log_warn "Caddyfile validation failed."
        return 1
    fi

    log_success "Caddyfile written to ${caddyfile}"
    return 0
}

_reload_caddy() {
    if check_command systemctl; then
        sudo systemctl enable caddy >> "${CLAWSPARK_LOG}" 2>&1 || true
        if sudo systemctl restart caddy >> "${CLAWSPARK_LOG}" 2>&1; then
            log_success "Caddy service restarted."
            return 0
        fi
    fi

    if check_command brew; then
        if brew services restart caddy >> "${CLAWSPARK_LOG}" 2>&1 || brew services start caddy >> "${CLAWSPARK_LOG}" 2>&1; then
            log_success "Caddy started via Homebrew services."
            return 0
        fi
    fi

    if check_command caddy; then
        sudo caddy reload --config /etc/caddy/Caddyfile >> "${CLAWSPARK_LOG}" 2>&1 && return 0
    fi

    return 1
}

_write_caddy_summary_files() {
    rm -f "${CLAWSPARK_DIR}/caddy-chat.url" "${CLAWSPARK_DIR}/caddy-dashboard.url"
    echo "true" > "${CLAWSPARK_DIR}/caddy.enabled"

    if [[ -n "${CADDY_DOMAIN:-}" ]]; then
        echo "https://${CADDY_DOMAIN}/__openclaw__/canvas/" > "${CLAWSPARK_DIR}/caddy-chat.url"
        if [[ -z "${CADDY_DASHBOARD_DOMAIN:-}" ]]; then
            echo "https://${CADDY_DOMAIN}/metrics/" > "${CLAWSPARK_DIR}/caddy-dashboard.url"
        fi
    fi

    if [[ -n "${CADDY_DASHBOARD_DOMAIN:-}" ]]; then
        echo "https://${CADDY_DASHBOARD_DOMAIN}/" > "${CLAWSPARK_DIR}/caddy-dashboard.url"
    fi

    printf '\n'
    print_box \
        "${BOLD}Public URLs${RESET}" \
        "" \
        "$(_caddy_summary_line)" \
        "$(_caddy_dashboard_summary_line)" \
        "" \
        "If HTTPS issuance fails, verify DNS and that ports 80/443 are open." \
        "Caddy logs: sudo journalctl -u caddy --no-pager"
}

_caddy_summary_line() {
    if [[ -n "${CADDY_DOMAIN:-}" ]]; then
        printf 'Chat UI / API: %s' "https://${CADDY_DOMAIN}/__openclaw__/canvas/"
    else
        printf 'Chat UI / API: not configured'
    fi
}

_caddy_dashboard_summary_line() {
    if [[ -n "${CADDY_DASHBOARD_DOMAIN:-}" ]]; then
        printf 'Dashboard    : %s' "https://${CADDY_DASHBOARD_DOMAIN}/"
    elif [[ -n "${CADDY_DOMAIN:-}" ]]; then
        printf 'Dashboard    : %s' "https://${CADDY_DOMAIN}/metrics/"
    else
        printf 'Dashboard    : not configured'
    fi
}

_trim_value() {
    printf '%s' "$1" | xargs
}

_is_valid_domain() {
    local domain="$1"
    [[ "${domain}" =~ ^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}
